server:
  port: 9090

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///shiro-demo?serverTimezone=UTC
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

mybatis-plus:
  # 扫描 mapper.xml
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    jdbc-type-for-null: 'null'
    # 用于输出mybatis的sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
